### ISSUE TITLE
Error creating an index in ElasticSearch

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/arthur#6]
I followed instructions to run arthur (latest commit checkout in this repo), but I get an error:

```
$ arthurd -g -d redis://localhost/8 --es-index http://localhost:9200/items --log-path /tmp/logs --no-cacheTraceback (most recent call last):
  File "/tmp/test2/bin/arthurd", line 225, in <module>
    main()
  File "/tmp/test2/bin/arthurd", line 88, in main
    writer = ElasticItemsWriter(args.es_index)
  File "/tmp/test2/lib/python3.5/site-packages/arthur/writers.py", line 71, in __init__
    was_created = self.create_index(self.idx_url, clean=clean)
  File "/tmp/test2/lib/python3.5/site-packages/arthur/writers.py", line 138, in create_index
    raise ElasticSearchError(cause=cause)
arthur.writers.ElasticSearchError: Error creating Elastic Search index http://localhost:9200/items
```

However, I can create that index manually, so it seems there is no issue with ElasticSearch.

Just in case it matters, it is ElasticSearch 6.0 (pre-releasse), and it is working nicely with other applications.

The log file reads:

```
[2017-07-19 23:52:31,500 - root - INFO] - King Arthur is on command.
[2017-07-19 23:52:31,501 - root - DEBUG] - Redis connection stablished with redis://localhost/8.
[2017-07-19 23:52:31,505 - urllib3.connectionpool - DEBUG] - Starting new HTTP connection (1): localhost
[2017-07-19 23:52:31,520 - urllib3.connectionpool - DEBUG] - http://localhost:9200 "GET /items HTTP/1.1" 404 None
[2017-07-19 23:52:31,522 - urllib3.connectionpool - DEBUG] - Starting new HTTP connection (1): localhost
[2017-07-19 23:52:31,528 - urllib3.connectionpool - DEBUG] - http://localhost:9200 "POST /items HTTP/1.1" 400 None
[2017-07-19 23:52:31,528 - arthur.writers - INFO] - Can't create index http://localhost:9200/items (400)
```

Curiously enough, in the ElasticSearch logs I see no access which could be attributed to arthur.

I tried with ElasticSearch 5.1.x as well, with the same results.

Any idea?

Just in case it matters, the result of pip freeze (I know there are many packages that are not needed, but I'm using the venv for some other stuff):

```
arthur==0.1.0.dev1
beautifulsoup4==4.6.0
certifi==2017.4.17
chardet==3.0.4
cheroot==5.7.0
CherryPy==11.0.0
click==6.7
feedparser==5.2.1
grimoire-elk==0.30.4
grimoire-kidash==0.30.4
grimoirelab-toolkit==0.1.0
idna==2.5
Jinja2==2.9.6
MarkupSafe==1.0
numpy==1.13.1
pandas==0.20.3
perceval==0.9.0
perceval-mozilla==0.1.1
perceval-opnfv==0.1.0
pkg-resources==0.0.0
portend==2.1.2
PyMySQL==0.7.11
python-dateutil==2.6.1
pytz==2017.2
redis==2.10.5
requests==2.18.1
rq==0.8.0
six==1.10.0
sortinghat==0.4.0
SQLAlchemy==1.1.11
tempora==1.8
urllib3==1.21.1
```

**Comment by nuriguri** [comment]
@jgbarah 
i also face this problem. did you resolve this problem?

**Comment by jgbarah** [comment]
Which version are you using @nuriguri ? I was told this was solved in recent versions of the stack.

**Comment by nuriguri** [comment]
@jgbarah 
Thanks for replying, but i already used latest arthur branch.. ~Should i use recent elasticsearch? 
And where can i see the solution for this problem?

**Comment by jgbarah** [comment]
I'm going to check that myself, and I will come back to you. @acs, @sduenas, can you have a look at this as well?

**Comment by sduenas** [comment]
Newer versions of ElasticSearch changed the way indexes and mappings are created in the server. The PR #10 fixes all these problems.
